workflows:
  salaryinfo-ios-fix:
    name: SalaryInfo iOS Build (Push Enabled)
    instance_type: mac_mini_m2
    max_build_duration: 75

    environment:
      groups:
        - appstore_credentials

      vars:
        BUNDLE_ID: "com.pocket.salaryinfo"
        APP_STORE_APPLE_ID: 6756042000
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_BUILD_NAME: "1.0.12"
        FLUTTER_BUILD_NUMBER: "31"   # ⬅️ زد الرقم دائمًا

      flutter: "3.22.0"
      xcode: latest
      cocoapods: default

    scripts:
      # =========================================================
      # 1️⃣ Code signing (Push Notifications INCLUDED)
      # =========================================================
      - name: Setup code signing
        script: |
          set -e
          keychain initialize

          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

          keychain add-certificates
          xcode-project use-profiles --profile-type app-store

      # =========================================================
      # 2️⃣ Clean everything (prevent cached entitlements)
      # =========================================================
      - name: Force clean Flutter & iOS
        script: |
          set -e
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/.symlinks ios/build ios/Runner.xcworkspace
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          pod cache clean --all
          rm -rf ~/Library/Caches/CocoaPods
          echo "✅ Clean complete"

      # =========================================================
      # 3️⃣ Get Flutter packages
      # =========================================================
      - name: Get Flutter packages
        script: |
          set -e
          flutter pub get
          echo "✅ Flutter packages installed"

      # =========================================================
      # 4️⃣ Install CocoaPods
      # =========================================================
      - name: Install CocoaPods
        script: |
          set -e
          cd ios
          pod install --repo-update
          cd ..
          echo "✅ Pods installed"

      # =========================================================
      # 5️⃣ Build Flutter (⚠️ NO --no-codesign ❌)
      # =========================================================
      - name: Build Flutter iOS
        script: |
          set -e
          flutter build ios --release
          echo "✅ Flutter iOS build complete"

      # =========================================================
      # 6️⃣ Archive with Xcode (Push entitlements applied)
      # =========================================================
      - name: Create Xcode archive
        script: |
          set -e
          cd ios
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            -destination 'generic/platform=iOS' \
            archive
          cd ..
          echo "✅ Archive created"

      # =========================================================
      # 7️⃣ Export IPA
      # =========================================================
      - name: Export IPA
        script: |
          set -e
          cd ios
          xcodebuild \
            -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist /Users/builder/export_options.plist

          mkdir -p ../build/ios/ipa
          cp build/ipa/*.ipa ../build/ios/ipa/
          cd ..
          echo "✅ IPA exported"

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/Podfile.lock

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

      email:
        recipients:
          - hazajadded@gmail.com
        notify:
          success: true
          failure: true
