workflows:
  salaryinfo-ios:
    name: SalaryInfo iOS (Stable - FIXED)
    instance_type: mac_mini_m2
    max_build_duration: 75

    environment:
      groups:
        - appstore_credentials

      vars:
        BUNDLE_ID: "com.pocket.salaryinfo"
        APP_STORE_APPLE_ID: 6756042000
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_BUILD_NAME: "1.0.12"
        FLUTTER_BUILD_NUMBER: "12"  # ✅ Increment build number

      flutter: "3.22.0"
      xcode: latest
      cocoapods: default

    scripts:
      # --------------------------------------------------
      # 1) Deep Clean (IMPORTANT)
      # --------------------------------------------------
      - name: Deep Clean
        script: |
          set -e
          echo "🧹 Performing deep clean..."
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/.symlinks ios/build ios/Runner.xcworkspace
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          rm -rf .packages .flutter-plugins
          echo "✅ Deep clean completed"

      # --------------------------------------------------
      # 2) Setup code signing
      # --------------------------------------------------
      - name: Setup code signing
        script: |
          set -e
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles

      # --------------------------------------------------
      # 3) Get Flutter packages
      # --------------------------------------------------
      - name: Get Flutter packages
        script: |
          set -e
          flutter pub get

      # --------------------------------------------------
      # 4) Install CocoaPods (WITH VERBOSE)
      # --------------------------------------------------
      - name: Install CocoaPods
        script: |
          set -e
          cd ios
          pod repo update
          pod install --repo-update --verbose
          cd ..

      # --------------------------------------------------
      # 5) Create Xcode Archive
      # --------------------------------------------------
      - name: Create Xcode archive
        script: |
          set -e
          cd ios
          
          # ✅ Build with specific settings
          xcodebuild clean \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release

          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates \
            archive

          cd ..

      # --------------------------------------------------
      # 6) Verify architectures
      # --------------------------------------------------
      - name: Verify architectures
        script: |
          lipo -info ios/build/Runner.xcarchive/Products/Applications/Runner.app/Runner

      # --------------------------------------------------
      # 7) Export IPA with custom export options
      # --------------------------------------------------
      - name: Export IPA
        script: |
          set -e
          cd ios
          
          # Copy export_options.plist from project root
          cp ../export_options.plist export_options.plist
          
          xcodebuild \
            -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist export_options.plist \
            -allowProvisioningUpdates

          mkdir -p ../build/ios/ipa
          cp build/ipa/*.ipa ../build/ios/ipa/
          cd ..

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/Podfile.lock

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true