workflows:
  salaryinfo-ios-apns:
    name: SalaryInfo iOS with APNs
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      groups:
        - appstore_credentials
      
      vars:
        BUNDLE_ID: "com.pocket.salaryinfo"
        APP_STORE_APPLE_ID: 6756042000
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_BUILD_NAME: "1.0.11"
        FLUTTER_BUILD_NUMBER: "5"
        
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      # 🔐 Setup Code Signing
      - name: Setup keychain and certificates
        script: |
          set -e
          keychain initialize
          
          echo "🔐 Fetching signing certificates for $BUNDLE_ID"
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          
          keychain add-certificates
          xcode-project use-profiles
          
          echo "✅ Code signing configured"

      # 🧹 Deep Clean Project
      - name: Deep clean project
        script: |
          set -e
          echo "🧹 Deep cleaning project..."
          flutter clean
          
          # Clean everything
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/build
          rm -rf ios/DerivedData
          
          echo "✅ Project cleaned"

      # 📦 Install Dependencies
      - name: Install Flutter packages
        script: |
          set -e
          echo "📦 Installing Flutter packages..."
          flutter pub get
          
          echo "✅ Flutter packages installed"

      - name: Install iOS pods with Firebase
        script: |
          set -e
          echo "📱 Installing iOS pods with Firebase..."
          cd ios
          
          # Clean pod cache
          pod cache clean --all
          
          # Update CocoaPods repo
          pod repo update
          
          # Install pods with verbose output
          pod install --repo-update --clean-install --verbose
          
          echo "✅ iOS pods installed"
          cd ..

      # 🔍 Verify Firebase Configuration
      - name: Verify Firebase setup
        script: |
          set -e
          echo "🔍 Verifying Firebase configuration..."
          
          # Check GoogleService-Info.plist
          if [ -f "ios/Runner/GoogleService-Info.plist" ]; then
            echo "✅ GoogleService-Info.plist found"
            
            # Extract project ID
            PROJECT_ID=$(/usr/libexec/PlistBuddy -c "Print :PROJECT_ID" ios/Runner/GoogleService-Info.plist 2>/dev/null || echo "")
            if [ "$PROJECT_ID" = "scgfs-salary-app" ]; then
              echo "✅ Correct Firebase Project: $PROJECT_ID"
            else
              echo "⚠️ Unexpected Firebase Project: $PROJECT_ID"
            fi
          else
            echo "❌ GoogleService-Info.plist NOT FOUND!"
            exit 1
          fi
          
          echo "✅ Firebase configuration verified"

      # 🏗️ Build iOS App
      - name: Build iOS IPA
        script: |
          set -e
          echo "🏗️ Building iOS IPA..."
          
          # First build to generate files
          flutter build ios --release --no-codesign --verbose
          
          # Then build IPA
          flutter build ipa \
            --release \
            --build-name="$FLUTTER_BUILD_NAME" \
            --build-number="$FLUTTER_BUILD_NUMBER" \
            --export-options-plist=/Users/builder/export_options.plist \
            --verbose
          
          echo "✅ IPA built successfully"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - hazajadded@gmail.com
        notify:
          success: true
          failure: true
      
      app_store_connect:
        auth: integration
        submit_to_testflight: true