workflows:
  salaryinfo-ios-fix:
    name: SalaryInfo iOS Crash Fix
    instance_type: mac_mini_m2
    max_build_duration: 75

    environment:
      groups:
        - appstore_credentials
      
      vars:
        BUNDLE_ID: "com.pocket.salaryinfo"
        APP_STORE_APPLE_ID: 6756042000
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_BUILD_NAME: "1.0.11"
        FLUTTER_BUILD_NUMBER: "6"
        
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      # 🔐 Setup Code Signing
      - name: Setup keychain and certificates
        script: |
          set -e
          keychain initialize
          
          echo "🔐 Fetching signing certificates for $BUNDLE_ID"
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          
          keychain add-certificates
          xcode-project use-profiles
          
          echo "✅ Code signing configured"

      # 🧹 DEEP Clean Project
      - name: Deep clean project
        script: |
          set -e
          echo "🧹 Deep cleaning project..."
          
          # Clean Flutter
          flutter clean
          
          # Clean iOS
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/build
          rm -rf ios/Runner.xcworkspace
          rm -rf ios/DerivedData
          
          # Clean Flutter cache
          rm -rf ~/.pub-cache
          
          echo "✅ Project deep cleaned"

      # 📦 Install Flutter packages
      - name: Install Flutter packages
        script: |
          set -e
          echo "📦 Installing Flutter packages..."
          flutter pub get
          
          echo "✅ Flutter packages installed"

      # 🔧 Verify Firebase files
      - name: Verify Firebase configuration
        script: |
          set -e
          echo "🔍 Verifying Firebase configuration..."
          
          # Check GoogleService-Info.plist exists
          if [ -f "ios/Runner/GoogleService-Info.plist" ]; then
            echo "✅ GoogleService-Info.plist found"
            
            # Check content
            PROJECT_ID=$(/usr/libexec/PlistBuddy -c "Print :PROJECT_ID" ios/Runner/GoogleService-Info.plist 2>/dev/null || echo "NOT_FOUND")
            BUNDLE_ID_PLIST=$(/usr/libexec/PlistBuddy -c "Print :BUNDLE_ID" ios/Runner/GoogleService-Info.plist 2>/dev/null || echo "NOT_FOUND")
            
            echo "📊 Firebase Project ID: $PROJECT_ID"
            echo "📊 Bundle ID in plist: $BUNDLE_ID_PLIST"
            
            if [ "$PROJECT_ID" = "scgfs-salary-app" ]; then
              echo "✅ Correct Firebase Project"
            else
              echo "⚠️ Unexpected Firebase Project"
            fi
          else
            echo "❌ GoogleService-Info.plist NOT FOUND!"
            exit 1
          fi
          
          echo "✅ Firebase configuration verified"

      # 📱 Install iOS pods
      - name: Install iOS pods
        script: |
          set -e
          echo "📱 Installing iOS pods..."
          cd ios
          
          # Clean pod cache
          pod cache clean --all
          
          # Deintegrate if needed
          pod deintegrate || true
          
          # Install pods with verbose output
          pod install --repo-update --verbose
          
          echo "✅ iOS pods installed"
          cd ..

      # 🏗️ Build iOS App
      - name: Build iOS IPA
        script: |
          set -e
          echo "🏗️ Building iOS IPA..."
          
          # Build with verbose output
          flutter build ipa \
            --release \
            --build-name="$FLUTTER_BUILD_NAME" \
            --build-number="$FLUTTER_BUILD_NUMBER" \
            --export-options-plist=export_options.plist \
            --verbose
          
          echo "✅ IPA built successfully"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - ios/Podfile.lock

    publishing:
      email:
        recipients:
          - hazajadded@gmail.com
        notify:
          success: true
          failure: true
      
      app_store_connect:
        auth: integration
        submit_to_testflight: true