workflows:
  salaryinfo-ios:
    name: SalaryInfo iOS (Simplified Build)
    instance_type: mac_mini_m2
    max_build_duration: 75

    environment:
      groups:
        - appstore_credentials

      vars:
        BUNDLE_ID: "com.pocket.salaryinfo"
        APP_STORE_APPLE_ID: 6756042000
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_BUILD_NAME: "1.0.12"
        FLUTTER_BUILD_NUMBER: "12"

      flutter: "3.22.0"
      xcode: latest
      cocoapods: default

    scripts:
      # --------------------------------------------------
      # 1) Basic Clean (No deep clean needed)
      # --------------------------------------------------
      - name: Basic Clean
        script: |
          set -e
          echo "🧹 Basic clean..."
          flutter clean
          echo "✅ Clean completed"

      # --------------------------------------------------
      # 2) Setup code signing
      # --------------------------------------------------
      - name: Setup code signing
        script: |
          set -e
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles

      # --------------------------------------------------
      # 3) Get Flutter packages
      # --------------------------------------------------
      - name: Get Flutter packages
        script: |
          set -e
          flutter pub get
          echo "✅ Flutter packages fetched"

      # --------------------------------------------------
      # 4) Simple pod install
      # --------------------------------------------------
      - name: Install CocoaPods
        script: |
          set -e
          cd ios
          # Simple pod install without verbose output
          pod install --repo-update
          cd ..
          echo "✅ CocoaPods installed"

      # --------------------------------------------------
      # 5) Build iOS app (Simplified)
      # --------------------------------------------------
      - name: Build iOS app
        script: |
          set -e
          flutter build ipa \
            --release \
            --export-options-plist=/Users/builder/export_options.plist
          echo "✅ iOS build completed"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true