workflows:
  salaryinfo-ios-fix:
    name: SalaryInfo iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 75

    environment:
      groups:
        - appstore_credentials
      
      vars:
        BUNDLE_ID: "com.pocket.salaryinfo"
        APP_STORE_APPLE_ID: 6756042000
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_BUILD_NAME: "1.0.11"
        FLUTTER_BUILD_NUMBER: "6"
        
      flutter: "3.22.0"
      xcode: latest
      cocoapods: default

    scripts:
      - name: Setup code signing
        script: |
          set -e
          keychain initialize
          
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          
          keychain add-certificates
          xcode-project use-profiles

      - name: Deep clean
        script: |
          set -e
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/.symlinks ios/build
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          pod cache clean --all
          rm -rf ~/Library/Caches/CocoaPods

      - name: Get Flutter packages
        script: |
          set -e
          flutter pub get

      - name: Verify Firebase config
        script: |
          set -e
          if [ ! -f "ios/Runner/GoogleService-Info.plist" ]; then
            echo "❌ GoogleService-Info.plist NOT FOUND!"
            exit 1
          fi
          echo "✅ Firebase configuration present"

      - name: Verify Podfile has Firebase fix
        script: |
          set -e
          if ! grep -q "CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES" ios/Podfile; then
            echo "❌ ERROR: Podfile missing Firebase modular header fix!"
            echo ""
            echo "Your ios/Podfile must include this in post_install:"
            echo "config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'"
            echo ""
            exit 1
          fi
          echo "✅ Podfile has Firebase fix"

      - name: Update CocoaPods specs
        script: |
          set -e
          pod repo update

      - name: Install iOS pods (with retry)
        script: |
          set -e
          cd ios
          
          for ATTEMPT in 1 2 3; do
            echo "════════════════════════════════════════"
            echo "Pod Install Attempt $ATTEMPT of 3"
            echo "════════════════════════════════════════"
            
            if pod install --repo-update --verbose; then
              echo "✅ Pod install succeeded!"
              cd ..
              exit 0
            fi
            
            echo "❌ Pod install failed on attempt $ATTEMPT"
            
            if [ $ATTEMPT -lt 3 ]; then
              echo "Cleaning for retry..."
              rm -rf Pods Podfile.lock .symlinks/plugins
              pod cache clean --all
              sleep 10
            fi
          done
          
          echo "❌ Pod install failed after 3 attempts"
          cd ..
          exit 1

      - name: Build iOS (no codesign)
        script: |
          set -e
          # Build Flutter framework and app without creating IPA
          # This WON'T upgrade Podfile because we already ran pod install
          flutter build ios --release --no-codesign

      - name: Create archive
        script: |
          set -e
          cd ios
          
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates \
            archive
          
          echo "✅ Archive created"
          cd ..

      - name: Export IPA
        script: |
          set -e
          cd ios
          
          xcodebuild \
            -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist /Users/builder/export_options.plist \
            -allowProvisioningUpdates
          
          # Copy to Flutter's expected location
          mkdir -p ../build/ios/ipa
          cp build/ipa/*.ipa ../build/ios/ipa/
          
          echo "✅ IPA exported"
          ls -lh ../build/ios/ipa/
          
          cd ..

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - ios/Podfile.lock

    publishing:
      email:
        recipients:
          - hazajadded@gmail.com
        notify:
          success: true
          failure: true
      
      app_store_connect:
        auth: integration
        submit_to_testflight: true