workflows:
  salaryinfo-ios:
    name: SalaryInfo iOS (Firebase Fixed)
    instance_type: mac_mini_m2
    max_build_duration: 90

    environment:
      groups:
        - appstore_credentials

      vars:
        BUNDLE_ID: "com.pocket.salaryinfo"
        APP_STORE_APPLE_ID: 6756042000
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_BUILD_NAME: "1.0.12"
        FLUTTER_BUILD_NUMBER: "12"
        COCOAPODS_DISABLE_STATS: "true"

      flutter: "3.22.0"
      xcode: latest
      cocoapods: default

    scripts:
      # --------------------------------------------------
      # 1) Enhanced Clean Process
      # --------------------------------------------------
      - name: Enhanced Clean
        script: |
          set -e
          echo "🧹 Enhanced cleaning process..."
          
          # Flutter clean
          flutter clean
          
          # Remove iOS build artifacts
          rm -rf ios/Pods
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/Flutter.framework
          rm -rf ios/Flutter/Flutter.podspec
          rm -rf ios/Runner.xcworkspace
          rm -f ios/Podfile.lock
          
          # Clear pod cache
          pod cache clean --all || true
          
          echo "✅ Enhanced clean completed"

      # --------------------------------------------------
      # 2) Setup code signing
      # --------------------------------------------------
      - name: Setup code signing
        script: |
          set -e
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles

      # --------------------------------------------------
      # 3) Get Flutter packages
      # --------------------------------------------------
      - name: Get Flutter packages
        script: |
          set -e
          flutter pub get
          echo "✅ Flutter packages fetched"

      # --------------------------------------------------
      # 4) Copy fixed Podfile and install CocoaPods
      # --------------------------------------------------
      - name: Setup CocoaPods with Firebase fixes
        script: |
          set -e
          cd ios
          
          # Copy the fixed Podfile (make sure it's in your repository)
          echo "📄 Using fixed Podfile for Firebase compatibility"
          
          # Update CocoaPods repo
          echo "🔄 Updating CocoaPods repo..."
          pod repo update
          
          # Install with verbose output for debugging
          echo "📦 Installing CocoaPods dependencies..."
          pod install --verbose --clean-install
          
          cd ..
          echo "✅ CocoaPods setup completed with Firebase fixes"

      # --------------------------------------------------
      # 5) Firebase Configuration Check
      # --------------------------------------------------
      - name: Verify Firebase Configuration
        script: |
          set -e
          echo "🔥 Verifying Firebase configuration..."
          
          # Check if firebase_options.dart exists
          if [ -f "lib/firebase_options.dart" ]; then
            echo "✅ firebase_options.dart found"
          else
            echo "❌ firebase_options.dart missing"
            exit 1
          fi
          
          # Check iOS workspace
          if [ -f "ios/Runner.xcworkspace/contents.xcworkspacedata" ]; then
            echo "✅ Xcode workspace created successfully"
          else
            echo "❌ Xcode workspace not found"
            exit 1
          fi
          
          echo "✅ Firebase configuration verified"

      # --------------------------------------------------
      # 6) Build iOS app with enhanced settings
      # --------------------------------------------------
      - name: Build iOS app
        script: |
          set -e
          echo "🔨 Building iOS app with Firebase fixes..."
          
          flutter build ipa \
            --release \
            --export-options-plist=/Users/builder/export_options.plist \
            --verbose
            
          echo "✅ iOS build completed successfully"

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/Runner.xcarchive/**/*

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        
      email:
        recipients:
          - developer@scgfs.gov.iq
        notify:
          success: true
          failure: true