name: salaryinfo
description: Ø¨ÙˆØ§Ø¨Ø© Ø§Ù„Ù…ÙˆØ¸Ù Ø§Ù„Ø±Ù‚Ù…ÙŠØ© - Ø§Ù„Ø´Ø±ÙƒØ© Ø§Ù„Ø¹Ø§Ù…Ø© Ù„ØªØ¹Ø¨Ø¦Ø© ÙˆØ®Ø¯Ù…Ø§Øª Ø§Ù„ØºØ§Ø²
publish_to: "none"

version: 1.0.14+20
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¥ Firebase
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  http: ^1.1.0

  # ðŸŒ WebView
  webview_flutter: ^4.4.4
  webview_flutter_android: ^4.9.0
  webview_flutter_wkwebview: ^3.22.0

  # ðŸŽ¨ UI
  # âš ï¸ IMPORTANT: Removed '^' to lock exact version 6.2.1
  # This prevents auto-upgrading to 6.3.0 which breaks the build
  google_fonts: 8.0.1

  # ðŸ’¾ Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  device_info_plus: ^11.0.0
  permission_handler: ^12.0.1
  gal: ^2.3.2
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^19.5.0
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  provider: ^6.1.5+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
