workflows:
  salaryinfo-ios:
    name: SalaryInfo iOS (Stable)
    instance_type: mac_mini_m2
    max_build_duration: 75

    environment:
      groups:
        - appstore_credentials

      vars:
        BUNDLE_ID: "com.pocket.salaryinfo"
        APP_STORE_APPLE_ID: 6756042000
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_BUILD_NAME: "1.0.11"
        FLUTTER_BUILD_NUMBER: "9"

      flutter: "3.22.0"
      xcode: latest
      cocoapods: default

    scripts:
      # --------------------------------------------------
      # 1) Code signing
      # --------------------------------------------------
      - name: Setup code signing
        script: |
          set -e
          keychain initialize

          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

          keychain add-certificates
          xcode-project use-profiles

      # --------------------------------------------------
      # 2) Clean project (SAFE CLEAN ONLY)
      # --------------------------------------------------
      - name: Clean project
        script: |
          set -e
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/.symlinks ios/build
          echo "✅ Safe clean completed"

      # --------------------------------------------------
      # 3) Get Flutter packages
      # --------------------------------------------------
      - name: Get Flutter packages
        script: |
          set -e
          flutter pub get
          echo "✅ Flutter packages installed"

      # --------------------------------------------------
      # 4) Install CocoaPods (NO aggressive cache delete)
      # --------------------------------------------------
      - name: Install CocoaPods
        script: |
          set -e
          cd ios
          pod repo update
          pod install --repo-update
          cd ..
          echo "✅ Pods installed"

      # --------------------------------------------------
      # 5) Build Flutter iOS framework
      # --------------------------------------------------
      - name: Build Flutter framework
        script: |
          set -e
          flutter build ios --release --no-codesign
          echo "✅ Flutter framework built"

      # --------------------------------------------------
      # 6) Create Xcode archive
      # --------------------------------------------------
      - name: Create Xcode archive
        script: |
          set -e
          cd ios

          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            -destination 'generic/platform=iOS' \
            archive

          cd ..
          echo "✅ Archive created"

      # --------------------------------------------------
      # 7) Export IPA
      # --------------------------------------------------
      - name: Export IPA
        script: |
          set -e
          cd ios

          xcodebuild \
            -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist /Users/builder/export_options.plist

          mkdir -p ../build/ios/ipa
          cp build/ipa/*.ipa ../build/ios/ipa/

          cd ..
          echo "✅ IPA exported"
          ls -lh build/ios/ipa/

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/Podfile.lock

    publishing:
      email:
        recipients:
          - hazajadded@gmail.com
        notify:
          success: true
          failure: true

      app_store_connect:
        auth: integration
        submit_to_testflight: true
