// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo6n3xKlwC6qRat8sZnAf2pIOtwAD0mY4',
    appId: '1:625120325992:web:f96e4fac3656a8de4466dd',
    messagingSenderId: '625120325992',
    projectId: 'scgfs-salary-app',
    authDomain: 'scgfs-salary-app.firebaseapp.com',
    storageBucket: 'scgfs-salary-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo6n3xKlwC6qRat8sZnAf2pIOtwAD0mY4',
    appId: '1:625120325992:android:f96e4fac3656a8de4466dd',
    messagingSenderId: '625120325992',
    projectId: 'scgfs-salary-app',
    storageBucket: 'scgfs-salary-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo6n3xKlwC6qRat8sZnAf2pIOtwAD0mY4',
    appId: '1:625120325992:ios:f96e4fac3656a8de4466dd',
    messagingSenderId: '625120325992',
    projectId: 'scgfs-salary-app',
    storageBucket: 'scgfs-salary-app.firebasestorage.app',
    iosBundleId: 'com.pocket.salaryinfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo6n3xKlwC6qRat8sZnAf2pIOtwAD0mY4',
    appId: '1:625120325992:ios:f96e4fac3656a8de4466dd',
    messagingSenderId: '625120325992',
    projectId: 'scgfs-salary-app',
    storageBucket: 'scgfs-salary-app.firebasestorage.app',
    iosBundleId: 'com.pocket.salaryinfo',
  );
}
